pro_stage_accueil:
    path: /
    controller: App\Controller\ProStageController::index

pro_stage_filtreEntreprise:
    path: /entreprise
    controller: App\Controller\ProStageController::filtreEntreprise

pro_stage_entreprise:
    path: /entreprise/{entreprise_ID}
    controller: App\Controller\ProStageController::entreprise

pro_stage_filtreFormations:
    path: /formation
    controller: App\Controller\ProStageController::filtreFormations

pro_stage_formations:
    path: /formation/{formation_ID}
    controller: App\Controller\ProStageController::formations

pro_stage_stages:
    path: /stages/{id}
    controller: App\Controller\ProStageController::stages
