pro_stage_accueil:
    path: /
    controller: App\Controller\ProStageController::index

pro_stage_filtreEntreprise:
    path: /Entreprises
    controller: App\Controller\ProStageController::filtreEntreprise

pro_stage_entreprise:
    path: /Entreprises/{entreprise_ID}
    controller: App\Controller\ProStageController::entreprise

pro_stage_filtreFormations:
    path: /Formations
    controller: App\Controller\ProStageController::filtreFormations

pro_stage_formations:
    path: /Formations/{formation_ID}
    controller: App\Controller\ProStageController::formations

pro_stage_stages:
    path: /Stages/{stage}
    controller: App\Controller\ProStageController::stages

pro_stage_ajouterEntreprise:
    path: /AjouterEntreprise
    controller: App\Controller\ProStageController::AjouterEntreprise

pro_stage_modifierEntreprise:
    path: /Modifier/{id}
    controller: App\Controller\ProStageController::ModifierEntreprise

pro_stage_ajouter:
    path: /Ajouter
    controller: App\Controller\ProStageController::AjouterStage
